CREATE TABLE Student (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    fullName VARCHAR(255) NOT NULL,
    password  VARCHAR(255) NOT NULL,
    school VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    major VARCHAR(255) NOT NULL,
    linkedinId VARCHAR(255)
);